name: Delete branch after PR merge

on:
  pull_request:
    types:
      - closed

jobs:
  delete_branch:
    if: github.event.pull_request.merged == true && (startsWith(github.event.pull_request.head.ref, 'feat') || startsWith(github.event.pull_request.head.ref, 'fix'))
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Change this line to grant write permissions
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Delete branch
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git push origin --delete ${{ github.event.pull_request.head.ref }}
